Repository ansible-collections/cloud.terraform, pull requests merged in 2024-05, with the labels that each got.

#123 docs: fix indents in aap guide
  docs/docsite/rst/guide_aap.rst
Labels: mergeit, safe to test

#124 Change ansible provider version to latest
  tests/integration/targets/terraform_provider/ansible_provider.tf
  tests/integration/targets/terraform_provider/modules/example/provider.tf
  tests/integration/targets/terraform_provider/modules/nested_module/provider.tf
Labels: mergeit, safe to test

#125 Add the configs so that we can use the patchback bot for semi-automated back ports
  .github/patchback.yml
Labels: mergeit, safe to test

#128 [Manual backport stable-2] Patchback/backports/stable 2/ad19e5b33b15d566e2979aa471c71902bb9b588d/pr 116
  .github/workflows/integration-tests.yaml
  .gitignore
  plugins/inventory/terraform_provider.py
  plugins/inventory/terraform_state.py
  plugins/module_utils/terraform_commands.py
  plugins/plugin_utils/base.py
  plugins/plugin_utils/common.py
  run_mypy.sh
  test-requirements.txt
  tests/integration/requirements.txt
  tests/integration/requirements.yml
  tests/integration/targets/inventory_terraform_state_aws/aliases
  tests/integration/targets/inventory_terraform_state_aws/runme.sh
  tests/integration/targets/inventory_terraform_state_aws/setup.yml
  tests/integration/targets/inventory_terraform_state_aws/teardown.yml
  tests/integration/targets/inventory_terraform_state_aws/templates/aws_credentials.sh.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/backend.hcl.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory_with_backend_files.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory_with_compose.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory_with_constructed.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory_with_hostname.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/templates/main.tf.j2
  tests/integration/targets/inventory_terraform_state_aws/test.yml
  tests/integration/targets/inventory_terraform_state_aws/vars/main.yml
  tests/integration/targets/inventory_terraform_state_azurerm/aliases
  tests/integration/targets/inventory_terraform_state_azurerm/runme.sh
  tests/integration/targets/inventory_terraform_state_azurerm/setup.yml
  tests/integration/targets/inventory_terraform_state_azurerm/teardown.yml
  tests/integration/targets/inventory_terraform_state_azurerm/templates/azure_credentials.sh.j2
  tests/integration/targets/inventory_terraform_state_azurerm/templates/inventory.yml.j2
  tests/integration/targets/inventory_terraform_state_azurerm/templates/main.tf.j2
  tests/integration/targets/inventory_terraform_state_azurerm/test.yml
  tests/integration/targets/inventory_terraform_state_azurerm/vars/main.yml
  tests/integration/targets/inventory_terraform_state_google/aliases
  tests/integration/targets/inventory_terraform_state_google/runme.sh
  tests/integration/targets/inventory_terraform_state_google/setup.yml
  tests/integration/targets/inventory_terraform_state_google/teardown.yml
  tests/integration/targets/inventory_terraform_state_google/templates/gcp_credentials.sh.j2
  tests/integration/targets/inventory_terraform_state_google/templates/inventory.yml.j2
  tests/integration/targets/inventory_terraform_state_google/templates/main.tf.j2
  tests/integration/targets/inventory_terraform_state_google/test.yml
  tests/integration/targets/inventory_terraform_state_google/vars/main.yml
  tests/unit/plugins/inventory/test_terraform_provider.py
  tests/unit/plugins/inventory/test_terraform_state.py
  tests/unit/plugins/plugin_utils/test_base.py
  tests/unit/plugins/plugin_utils/test_common.py
  tox.ini
Labels: mergeit, safe to test, skip-changelog

#132 [Manual backport stable-2] Patchback/backports/stable 2/d9756afa152f2fbf881aab6553191920df27f70d/pr 120
  plugins/inventory/terraform_state.py
Labels: mergeit, safe to test, skip-changelog

#133 [Manual backport stable-2] Patchback/backports/stable 2/da9b61ea4eb30c804ec97ce0f3af91cca6a3456b/pr 121
  plugins/inventory/terraform_state.py
  tests/integration/targets/inventory_terraform_state_aws/templates/inventory_with_constructed.yml.j2
  tests/integration/targets/inventory_terraform_state_aws/test.yml
  tests/unit/plugins/inventory/test_terraform_state.py
Labels: mergeit, safe to test, skip-changelog

#137 Increase the version specified in the galaxy.yml file to point the next major release
  galaxy.yml
Labels: mergeit, safe to test, skip-changelog

#136 Docs links update after branching stable-3
  README.md
  docs/cloud.terraform.plan_stash_module.rst
  docs/cloud.terraform.terraform_state_inventory.rst
  roles/git_plan/README.md
  roles/inventory_from_outputs/README.md
Labels: mergeit, safe to test, skip-changelog

#135 Prepare Release 2.1.0
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20240217-fix-awscc-integration-test.yaml
  docs/cloud.terraform.plan_stash_module.rst
  docs/cloud.terraform.terraform_state_inventory.rst
  galaxy.yml
Labels: safe to test

#138 Drop support for ansible-core < 2.15
  README.md
  changelogs/fragments/ansible-core-version-increase.yml
  meta/runtime.yml
Labels: mergeit, safe to test, backport-3

#140 Prep cloud.terraform 3.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/20240217-fix-awscc-integration-test.yaml
  changelogs/fragments/ansible-core-version-increase.yml
  docs/cloud.terraform.terraform_module.rst
  galaxy.yml
Labels: mergeit, safe to test

#141 add collection roles galaxy information
  changelogs/fragments/20240527-roles-add-description.yml
  roles/git_plan/meta/main.yml
  roles/inventory_from_outputs/meta/main.yml
Labels: safe to test, backport-2, backport-3
